### ISSUE TITLE
Query to get acc balances

### ISSUE THREAD

**Issue by stevenkingsley** [smallstone-uk/sle-epos#16]
SELECT eaTitle, sum( eiNet + eiVAT ) AS balance
FROM tblepos_account
LEFT JOIN tblepos_items ON eaID = eiAccID
WHERE eaMenu = 'Yes'
GROUP BY eaID

This can be used to list the account names with their balances.

**Comment by jameslkingsley** [comment]
Added to [EPOSAccount](https://github.com/smallstone-uk/sle-epos/blob/master/App/EPOSAccount.cfc#L27-L42).
