### ISSUE TITLE
receipt printer not working

### ISSUE THREAD

**Issue by stevenkingsley** [smallstone-uk/sle-epos#18]
getting a 404 error when printing the receipt.
http://dev.sle-epos.lan/js/StarWebPrintTrader.js/

**Comment by jameslkingsley** [comment]
Are you sure it's 404'ing on the JavaScript file and not on the connection to the printer?

**Comment by stevenkingsley** [comment]
Yes it’s got a slash after the .js file name

**Comment by jameslkingsley** [comment]
Fixed in 7e14188. Run this in the root of the project to update: `git pull --recurse-submodules`
